### ISSUE TITLE
Performance concerns with many concurrent clients

### ISSUE THREAD

**Issue by allgeek** [tylertreat/bench#7]
Forgive me for using an issue for something more conversational at this point - if there's a better / separate channel we can discuss in let me know.

I'm working on benchmarking a system that has (expectedly) fairly high latency characteristics (think on the order of 100ms), but should easily handle a large number of concurrent requests and overall throughput (1000+ TPS).  In order to achieve those kinds of rates with those latencies, it'd require at least 100 concurrent clients.  We'd like to test at larger scales as well.

Per [bench.go#L229](https://github.com/tylertreat/bench/blob/7ad29b129902866990b15c34179baad559f1c6cd/bench.go#L229), each client uses a busy-spin loop to perform rate limiting.  Can you discuss a bit more of the rationale for that?  I'm assuming it's to minimize potential scheduler delays that could be incurred by using a time.Ticker or similar mechanism to sleep/wake the goroutine - but as soon as we have more client goroutines than CPU cores / GOMAXPROCS, I'd think contention from this busy-spin loop would make matters worse.

Did you have actual issues that necessitated that busy-spin?  Have you thought through other potential designs?  I'm going to take a stab at an alternative approach (while still correcting for the coordinated omission problem), but I want to be sure I'm not overlooking something subtle that would invalidate the results, so I'd appreciate any insights you may have off hand..

**Comment by tylertreat** [comment]
It's a good question and you're right, the reason was (at least in theory) to minimize scheduler delays. However, this is probably only true if we're waiting a very short amount of time (like a microsecond). I haven't actually tried using something like `time.Ticker` instead, though I have no problem changing it if you discover it produces better results. PRs are welcome.

**Comment by wilriker** [comment]
I was experimenting with `time.Ticker` in this context today and it turned out there is a threshold where this starts to make a difference:

If `requestRate / connections <= 10,000`, i.e. `expectedInterval >= 100µs` (per connection) using `time.Ticker` results in a more precise schedule and at the same time a much lower CPU usage. For `expectedInterval < 100µs` the busy loop wins the contest for accuracy of the schedule but uses nearly 100% CPU (if number of connections is >= core count).

These values have been found on two different machines but both using an Intel Core i7 (different models though). The threshold might differ on other systems.

Best regards

Manuel
